name: Build V8 Disassembler

on:
  workflow_dispatch:
    inputs:
      v8_branch:
        description: 'V8 Version / Branch'
        required: true
        default: '13.2.152.27'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      V8_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.v8_branch || '13.2.152.27' }}
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install depot_tools
        # language=PowerShell
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git C:\depot_tools
          echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Fetch V8
        # language=PowerShell
        run: |
          fetch v8
          cd v8
          git checkout $env:V8_BRANCH
          gclient sync -v

      - name: Patch V8
        # language=PowerShell
        run: |
          ./patcher.ps1

      - name: Display Environment Info
        # language=PowerShell
        run: |
          clang++ --version
          echo "Environment Variables:"
          Get-ChildItem env:
          
      - name: Verify V8 Disassembler Source
        # language=PowerShell
        run: |
          if (-not (Test-Path "v8dasm.cpp")) {
            echo "Error: v8dasm.cpp not found in the project root directory!"
            exit 1
          }
          echo "Found v8dasm.cpp in the project root directory"

      - name: Build V8 Disassembler
        id: build
        # language=PowerShell
        run: |
          cd v8
          $release = "out.gn\x64.release"
          New-Item -ItemType Directory -Path $release -Force
          Set-Content -Path "$release\args.gn" -Value @"
          dcheck_always_on = false
          is_component_build = false
          is_debug = false
          target_cpu = "x64"
          use_custom_libcxx = false
          v8_monolithic = true
          v8_use_external_startup_data = false
          
          v8_static_library = true
          v8_enable_disassembler = true
          v8_enable_object_print = true
          v8_enable_sandbox = true
          v8_enable_pointer_compression = true
          v8_enable_pointer_compression_shared_cage = true
          v8_enable_external_code_space = true
          
          treat_warnings_as_errors = false
          "@
          gn gen $release
          
          # Build V8 libraries step by step to ensure they are properly generated
          echo "Building V8 base libraries..."
          ninja -C $release v8_libbase
          if ($LASTEXITCODE -ne 0) { 
              echo "Failed to build v8_libbase"
              exit 1 
          }
          
          echo "Building V8 platform libraries..."
          ninja -C $release v8_libplatform
          if ($LASTEXITCODE -ne 0) { 
              echo "Failed to build v8_libplatform"
              exit 1 
          }
          
          echo "Building V8 monolith..."
          ninja -C $release v8_monolith
          if ($LASTEXITCODE -ne 0) { 
              echo "Failed to build v8_monolith"
              exit 1 
          }
          
          # Verify library files exist and are valid
          $libFiles = @("$release\obj\v8_libbase.lib", "$release\obj\v8_libplatform.lib", "$release\obj\v8_monolith.lib")
          foreach ($lib in $libFiles) {
              if (-not (Test-Path $lib)) {
                  echo "Error: Library file $lib not found"
                  exit 1
              }
              $fileSize = (Get-Item $lib).Length
              if ($fileSize -lt 1000) {
                  echo "Error: Library file $lib appears to be too small ($fileSize bytes)"
                  exit 1
              }
              echo "Library $lib verified: $fileSize bytes"
          }
          
          # Compile v8dasm using MSVC first (more reliable on Windows)
          echo "Compiling v8dasm with MSVC..."
          cl ..\v8dasm.cpp /std:c++20 /I"include" /Fe:v8dasm.exe /link "$release\obj\v8_monolith.lib" "$release\obj\v8_libbase.lib" "$release\obj\v8_libplatform.lib" /LIBPATH:"$release\obj" /MACHINE:X64
          
          # Check if compilation was successful
          if ($LASTEXITCODE -ne 0) {
              echo "Failed to compile v8dasm with MSVC, trying clang++..."
              # Try clang++ with proper Windows library paths
              clang++ ..\v8dasm.cpp -std=c++20 -Iinclude -L"$release\obj" -lv8_monolith -lv8_libbase -lv8_libplatform -o v8dasm.exe -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_ENABLE_EXTERNAL_CODE_SPACE -ldbghelp -lwinmm -lsecur32
              
              if ($LASTEXITCODE -ne 0) {
                  echo "Failed to compile v8dasm with clang++, trying alternative linking..."
                  # Last resort: try direct object linking
                  clang++ ..\v8dasm.cpp -std=c++20 -Iinclude "$release\obj\v8_monolith.lib" "$release\obj\v8_libbase.lib" "$release\obj\v8_libplatform.lib" -o v8dasm.exe -ldbghelp -lwinmm -lsecur32
              }
          }
          
          # Verify executable was created
          if (-not (Test-Path "v8dasm.exe")) {
              echo "Error: v8dasm.exe was not created"
              exit 1
          }
          
          # Copy v8dasm.exe to output directory
          cp v8dasm.exe $release\
          
          # Check if executable exists in output directory
          if (Test-Path "$release\v8dasm.exe") {
              echo "V8 Disassembler compilation successful: $(Get-Item "$release\v8dasm.exe").Length bytes"
          } else {
              echo "Error: Failed to copy v8dasm.exe to output directory!"
              exit 1
          }

          $artifact = "v8dasm-$env:V8_BRANCH"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "artifact=$artifact"

      - name: Cleanup Artifact
        # language=PowerShell
        run: |
          cd v8\out.gn\x64.release
          Get-ChildItem
          Remove-Item -Path gen -Recurse -Force
          Remove-Item -Path obj -Recurse -Force
          # Keep v8dasm.exe and necessary library files

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact }}
          path: v8/out.gn/x64.release
          compression-level: 9
